<?xml version="1.0" encoding="utf-8"?><Database Name="SaleProject" Class="dbProjectDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.buy" Member="buys">
    <Type Name="buy">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="project_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="customer_buy" Member="customer" ThisKey="customer_id" OtherKey="id" Type="customer" IsForeignKey="true" />
      <Association Name="project_buy" Member="project" ThisKey="project_id" OtherKey="id" Type="project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.customer" Member="customers">
    <Type Name="customer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="full_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="customer_buy" Member="buys" ThisKey="id" OtherKey="customer_id" Type="buy" />
    </Type>
  </Table>
  <Table Name="dbo.project" Member="projects">
    <Type Name="project">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="image" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="category" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="publish_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="project_buy" Member="buys" ThisKey="id" OtherKey="project_id" Type="buy" />
    </Type>
  </Table>
</Database>